### PR TITLE
Addition of which key

### PR DESCRIPTION
**Pull request by Vanderscycle**
PR for the addition of which key.
Change to misc-util with the addition of a timeout time of 500 ms. whichkey.lua contains the default settings for which key and can be modified

reference:
https://github.com/folke/which-key.nvim

### CODE REVIEW

**Comment by siduck76** [comment]
its supposed to look like this by default? 

image

**Comment by Vanderscycle** [comment]
Looks about right, idk why mine displays over 4 rows vice 2 
whichKey

**Comment by Vanderscycle** [comment]
If you press <leader> for example and let it timeout, which-key will popout with only the <leader> bindings. Same with v and z. Bsc from any of the sub menus will bring you the "main" menu (the one you posted).

**Comment by siduck** [comment]
@Vanderscycle it has been added recently, I assume you dont use nvchad but reminding it xD

**Comment by siduck** [comment]
image
image

**Comment by Vanderscycle** [comment]
Glad to hear, I moved to Lunarvim which gave me the time and space to dive deeper into nvim api. NvChad, at the time, was changing very quickly and I didn't have the time to keep up.

**Pull request merged**
