### PR TITLE
Add `lspinstall` functionality

### PR DESCRIPTION
**Pull request by marvelman3284**
By using [williamboman/nvim-lsp-installer](https://github.com/williamboman/nvim-lsp-installer) I added an `lspinstall` function to easily allow users to install their own langauge servers. This could probably remove the hardcoded lsps in `nvim-lspcofig.lua` but i didn't want to remove anything yet.

### CODE REVIEW

**Review by siduck76 — COMMENTED** [review]
@marvelman3284 lua/mappings.lua should have bash by default

**Comment by marvelman3284** [comment]
@siduck76 I fixed `mappings.lua` and removed the duplicate functions. I choose to use williamboman/nvim-lsp-installer cause when I tried to implement kabouzeid/nvim-lspinstall it wasn't working and had crashed my nvim. I also didn't mess around with it for long before trying nvim-lsp-installer so you maybe be able to get it working.

**Comment by marvelman3284** [comment]
This had all originally started when I wanted to use the go lsp but couldn't get it working so I tried finding other solutions. I was really just looking for something to fix my issues even if it wasn't the most practical or efficient and decided that it could be a nice addition to the dots. So there could totally be a more efficient way to implement auto lsp installing that you might know of.

**Comment by siduck76** [comment]
I'll try  kabouzeid/nvim-lspinstall and let you know if it works for me , it supports more languages and we might use it.

**Review by siduck76 — APPROVED** [review]
lspinstall funcionality has been added now , check [repo](https://github.com/kabouzeid/nvim-lspinstal) to know currently supported languages; 

basic usage :LspInstall css

**Pull request merged**
