### PR TITLE
Changes to the readme

### PR DESCRIPTION
**Pull request by Vanderscycle**
Added the most usefull bindings from lsp config

### CODE REVIEW

**Review by siduck76 — APPROVED** [review]

**Comment by siduck76** [comment]
We'll keep some basic keybinds in the readme soon and soon add whickey.nvim!

**Comment by Vanderscycle** [comment]
I have whichkey.nvim working on my version. I can make a pr for it.

**Comment by siduck76** [comment]
idk about the config , is it hard to configure it? can you show me your config file for it.

**Comment by Vanderscycle** [comment]
It took me a fair amount of fiddling at the beginning. I'll make a pr with the changes that would entail to the main repo so that there's no confusion.

**Comment by siduck76** [comment]
there are many keybinds in our config , are you gonna include them all in whichkey :D

**Comment by Vanderscycle** [comment]
Nope, I have a few different bindings in my version, but I fork the most up-to-date version of your repo when I propose changes to be made. Impossing my bindings would be rude.

**Pull request merged**
